# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' computes the no of elements that are in the ith group in a
#' and the jth group in b
#'
#' @param a,b integer vectors
#' @param i,j,n integers
#' @keywords internal
nij <- function(a, b, i, j, n) {
    .Call(`_RankMetric_nij`, a, b, i, j, n)
}

#' computes Kendall's distance
#'
#' @param a,b integer vectors
#' @param n integer
#' @keywords internal
kendR <- function(a, b, n) {
    .Call(`_RankMetric_kendR`, a, b, n)
}

